# One-to-Many and Many-to-Many Joins - Lab

## Introduction

In this lab, you'll practice your knowledge on One-to-Many and Many-to-many relationships!

## Objectives

You will be able to:
- Query data including Many-to-Many relationships
- Write queries that make use of Join Tables

## One-to-Many and Many-to-Many Joins
<img src='Database-Schema.png' width=550>

In [3]:
#import libraries
import pandas as pd
import sqlite3

#create connection
conn = sqlite3.connect('data.sqlite', detect_types=sqlite3.PARSE_COLNAMES)

#create cursor
cur = conn.cursor()

In [4]:
#create function to handle query
def query(sql, head=0):
    cur.execute(sql)
    df = pd.DataFrame(cur.fetchall())
    df.columns = [i[0] for i in cur.description]
    if head == 1:
        return df.head()
    else:
        return df

## Employees and their Office (a One-to-One join)

Return a list of all of the employees with their first name, last name and the city and state of the office that they work out of (if they have one). Include all employees and order them by their first name, then their last name.

In [7]:
#Your code here
query("""select employees.firstName, employees.lastName, offices.city, offices.state from employees
left join offices on employees.officeCode = offices.officeCode
order by employees.firstName ASC, employees.lastName ASC;""")

   firstName   lastName           city       state
0       Andy     Fixter         Sydney
1    Anthony        Bow  San Francisco          CA
2      Barry      Jones         London
3      Diane     Murphy  San Francisco          CA
4   Foon Yue      Tseng            NYC          NY
5     George     Vanauf            NYC          NY
6     Gerard     Bondur          Paris
7     Gerard  Hernandez          Paris
8       Jeff   Firrelli  San Francisco          CA
9      Julie   Firrelli         Boston          MA
10     Larry       Bott         London
11    Leslie   Jennings  San Francisco          CA
12    Leslie   Thompson  San Francisco          CA
13      Loui     Bondur          Paris
14      Mami      Nishi          Tokyo  Chiyoda-Ku
15    Martin     Gerard          Paris
16      Mary  Patterson  San Francisco          CA
17    Pamela   Castillo          Paris
18     Peter      Marsh         Sydney
19     Steve  Patterson         Boston          MA
20       Tom       King         Sydney
21   William  Patterson         Sydney
22   Yoshimi       Kato          Tokyo  Chiyoda-Ku

## Customers and their Orders (a One-to-Many join)

Return a list of all of the customers. For each customer return a record for each of their order numbers, order dates and statuses.

In [10]:
# Your code here
query("""select cust.customerName, ord.orderDate, ord.status, ord.orderNumber from customers cust
left join orders ord on cust.customerNumber = ord.customerNumber
order by cust.customerName ASC, ord.orderDate ASC, ord.status, ord.orderNumber;""")

                     customerName   orderDate     status orderNumber
0                   ANG Resellers        None       None        None
1                  AV Stores, Co.  2003-03-18    Shipped       10110
2                  AV Stores, Co.  2004-10-14    Shipped       10306
3                  AV Stores, Co.  2004-11-17    Shipped       10332
4                    Alpha Cognac  2003-07-04    Shipped       10136
5                    Alpha Cognac  2003-11-08    Shipped       10178
6                    Alpha Cognac  2005-03-28    Shipped       10397
7          American Souvenirs Inc        None       None        None
8              Amica Models & Co.  2004-08-17    Shipped       10280
9              Amica Models & Co.  2004-09-09    Shipped       10293
10        Anna's Decorations, Ltd  2003-09-11    Shipped       10148
11        Anna's Decorations, Ltd  2003-11-04    Shipped       10169
12        Anna's Decorations, Ltd  2005-01-20    Shipped       10370
13        Anna's Decorations, Ltd  2005-03-09    Shipped       10391
14            Anton Designs, Ltd.        None       None        None
15     Asian Shopping Network, Co        None       None        None
16          Asian Treasures, Inc.        None       None        None
17              Atelier graphique  2003-05-20    Shipped       10123
18              Atelier graphique  2004-09-27    Shipped       10298
19              Atelier graphique  2004-11-25    Shipped       10345
20   Australian Collectables, Ltd  2003-11-21    Shipped       10193
21   Australian Collectables, Ltd  2004-07-02    Shipped       10265
22   Australian Collectables, Ltd  2005-05-09   Disputed       10415
23     Australian Collectors, Co.  2003-04-29    Shipped       10120
24     Australian Collectors, Co.  2003-05-21    Shipped       10125
25     Australian Collectors, Co.  2004-02-20    Shipped       10223
26     Australian Collectors, Co.  2004-11-24    Shipped       10342
27     Australian Collectors, Co.  2004-11-29    Shipped       10347
28    Australian Gift Network, Co  2003-09-25    Shipped       10152
29    Australian Gift Network, Co  2003-11-06    Shipped       10174
..                            ...         ...        ...         ...
320     The Sharp Gifts Warehouse  2005-04-22    On Hold       10407
321       Tokyo Collectables, Ltd  2004-06-15    Shipped       10258
322       Tokyo Collectables, Ltd  2004-11-23    Shipped       10339
323       Tokyo Collectables, Ltd  2005-01-26    Shipped       10372
324       Tokyo Collectables, Ltd  2005-04-22    Shipped       10408
325       Toms Spezialitäten, Ltd  2003-11-20    Shipped       10191
326       Toms Spezialitäten, Ltd  2004-10-16    Shipped       10310
327          Toys of Finland, Co.  2003-10-06    Shipped       10155
328          Toys of Finland, Co.  2004-09-30    Shipped       10299
329          Toys of Finland, Co.  2005-02-09    Shipped       10377
330             Toys4GrownUps.com  2003-08-25    Shipped       10145
331             Toys4GrownUps.com  2003-11-18    Shipped       10189
332             Toys4GrownUps.com  2005-01-12   Resolved       10367
333         UK Collectables, Ltd.  2003-10-06    Shipped       10302
334         UK Collectables, Ltd.  2004-06-01  Cancelled       10253
335         UK Collectables, Ltd.  2005-04-08    Shipped       10403
336               Vida Sport, Ltd  2004-02-22    Shipped       10225
337               Vida Sport, Ltd  2004-08-30    Shipped       10287
338               Vitachrome Inc.  2003-01-10    Shipped       10102
339               Vitachrome Inc.  2004-04-05    Shipped       10237
340               Vitachrome Inc.  2004-11-05    Shipped       10324
341      Volvo Model Replicas, Co  2003-03-24    Shipped       10112
342      Volvo Model Replicas, Co  2004-11-03    Shipped       10320
343      Volvo Model Replicas, Co  2004-11-09    Shipped       10326
344      Volvo Model Replicas, Co  2004-11-19    On Hold       10334
345              Warburg Exchange        None       None        None
346   West Coast Collectables Co.  2003-12-01    Shipped       10199
347   West Coast Collectables Co.  2004-01-29    Shipped       10215
348             giftsbymail.co.uk  2004-03-20    Shipped       10232
349             giftsbymail.co.uk  2004-11-01    Shipped       10316

[350 rows x 4 columns]

## Orders and their Order Details (another One-to-Many join)

Return a list of orders. For each order return a record for each order detail within the order.

In [12]:
# Your code here
query("""select ordtl.* from orders ord
left join orderdetails ordtl on ord.orderNumber = ordtl.orderNumber
order by ordtl.orderNumber, ordtl.orderLineNumber""")

     orderNumber productCode quantityOrdered priceEach orderLineNumber
0          10100    S24_3969              49     35.29               1
1          10100    S18_2248              50     55.09               2
2          10100    S18_1749              30    136.00               3
3          10100    S18_4409              22     75.46               4
4          10101    S18_2795              26    167.06               1
5          10101    S24_2022              46     44.35               2
6          10101    S24_1937              45     32.53               3
7          10101    S18_2325              25    108.06               4
8          10102    S18_1367              41     43.13               1
9          10102    S18_1342              39     95.55               2
10         10103    S24_2300              36    107.34               1
11         10103    S18_1097              35     94.50              10
12         10103    S10_1949              26    214.30              11
13         10103    S18_2949              27     92.19              12
14         10103    S18_3136              25     86.92              13
15         10103    S18_2957              35     61.84              14
16         10103    S24_4258              25     88.62              15
17         10103    S18_3320              46     86.31              16
18         10103    S18_2432              22     58.34               2
19         10103    S32_1268              31     92.46               3
20         10103    S10_4962              42    119.67               4
21         10103    S18_4600              36     98.07               5
22         10103   S700_2824              42     94.07               6
23         10103    S32_3522              45     63.35               7
24         10103    S12_1666              27    121.64               8
25         10103    S18_4668              41     40.75               9
26         10104    S12_3148              34    131.44               1
27         10104    S24_2840              44     30.41              10
28         10104    S32_2509              35     51.95              11
29         10104    S18_2319              29    122.73              12
...          ...         ...             ...       ...             ...
2966       10420    S24_2887              55    115.09               8
2967       10420    S24_2766              39     76.33               9
2968       10421    S18_2795              35    167.06               1
2969       10421    S24_2022              40     44.80               2
2970       10422    S18_1367              25     47.44               1
2971       10422    S18_1342              51     91.44               2
2972       10423    S18_2949              10     89.15               1
2973       10423    S18_3136              21     98.44               2
2974       10423    S18_2957              31     56.21               3
2975       10423    S24_4258              28     78.89               4
2976       10423    S18_3320              21     80.36               5
2977       10424   S700_2824              46     85.98               1
2978       10424    S32_3522              44     54.94               2
2979       10424    S12_1666              49    121.64               3
2980       10424    S18_4668              26     40.25               4
2981       10424    S18_1097              54    108.50               5
2982       10424    S10_1949              50    201.44               6
2983       10425    S24_1444              55     53.75               1
2984       10425    S18_2432              19     48.62              10
2985       10425    S32_1268              41     83.79              11
2986       10425    S10_4962              38    131.49              12
2987       10425    S18_4600              38    107.76              13
2988       10425    S50_1392              18     94.92               2
2989       10425    S18_2238              28    147.36               3
2990       10425    S12_4473              33     95.99               4
2991       10425    S24_2840              31     31.82               5
2992       10425    S32_2509              11     50.32               6
2993       10425    S18_2319              38    117.82               7
2994       10425    S18_3232              28    140.55               8
2995       10425    S24_2300              49    127.79               9

[2996 rows x 5 columns]

## Orders, Order details and Product Details (a Many-to-Many Join)

Return a list of the orders with the the order information, and all the product information for each product in the order.

In [16]:
# Your code here
query("""select ord.*, prod.* from orders ord
left join orderdetails ordtl on ordtl.orderNumber = ord.orderNumber
left join products prod on ordtl.productCode = prod.productCode
order by ord.orderNumber, ord.orderDate, ord.requiredDate, ord.shippedDate""")

,orderNumber,orderDate,requiredDate,shippedDate,status,comments,customerNumber,productCode,productName,productLine,productScale,productVendor,productDescription,quantityInStock,buyPrice,MSRP
0,10100,2003-01-06,2003-01-13,2003-01-10,Shipped,,363,S18_1749,1917 Grand Touring Sedan,Vintage Cars,1:18,Welly Diecast Productions,This 1:18 scale replica of the 1917 Grand Tour...,2724,86.70,170.00
1,10100,2003-01-06,2003-01-13,2003-01-10,Shipped,,363,S18_2248,1911 Ford Town Car,Vintage Cars,1:18,Motor City Art Classics,"Features opening hood, opening doors, opening ...",540,33.30,60.54
2,10100,2003-01-06,2003-01-13,2003-01-10,Shipped,,363,S18_4409,1932 Alfa Romeo 8C2300 Spider Sport,Vintage Cars,1:18,Exoto Designs,This 1:18 scale precision die cast replica fea...,6553,43.26,92.03
3,10100,2003-01-06,2003-01-13,2003-01-10,Shipped,,363,S24_3969,1936 Mercedes Benz 500k Roadster,Vintage Cars,1:24,Red Start Diecast,This model features grille-mounted chrome horn...,2081,21.75,41.03
4,10101,2003-01-09,2003-01-18,2003-01-11,Shipped,Check on availability.,128,S18_2325,1932 Model A Ford J-Coupe,Vintage Cars,1:18,Autoart Studio Design,This model features grille-mounted chrome horn...,9354,58.48,127.13
5,10101,2003-01-09,2003-01-18,2003-01-11,Shipped,Check on availability.,128,S18_2795,1928 Mercedes-Benz SSK,Vintage Cars,1:18,Gearbox Collectibles,This 1:18 replica features grille-mounted chro...,548,72.56,168.75
6,10101,2003-01-09,2003-01-18,2003-01-11,Shipped,Check on availability.,128,S24_1937,1939 Chevrolet Deluxe Coupe,Vintage Cars,1:24,Motor City Art Classics,This 1:24 scale die-cast replica of the 1939 C...,7332,22.57,33.19
7,10101,2003-01-09,2003-01-18,2003-01-11,Shipped,Check on availability.,128,S24_2022,1938 Cadillac V-16 Presidential Limousine,Vintage Cars,1:24,Classic Metal Creations,This 1:24 scale precision die cast replica of ...,2847,20.61,44.80
8,10102,2003-01-10,2003-01-18,2003-01-14,Shipped,,181,S18_1342,1937 Lincoln Berline,Vintage Cars,1:18,Motor City Art Classics,"Features opening engine cover, doors, trunk, a...",8693,60.62,102.74
9,10102,2003-01-10,2003-01-18,2003-01-14,Shipped,,181,S18_1367,1936 Mercedes-Benz 500K Special Roadster,Vintage Cars,1:18,Studio M Art Models,This 1:18 scale replica is constructed of heav...,8635,24.26,53.91
10,10103,2003-01-29,2003-02-07,2003-02-02,Shipped,,121,S10_1949,1952 Alpine Renault 1300,Classic Cars,1:10,Classic Metal Creations,Turnable front wheels; steering function; deta...,7305,98.58,214.30
11,10103,2003-01-29,2003-02-07,2003-02-02,Shipped,,121,S10_4962,1962 LanciaA Delta 16V,Classic Cars,1:10,Second Gear Diecast,Features include: Turnable front wheels; steer...,6791,103.42,147.74
12,10103,2003-01-29,2003-02-07,2003-02-02,Shipped,,121,S12_1666,1958 Setra Bus,Trucks and Buses,1:12,Welly Diecast Productions,"Model features 30 windows, skylights & glare r...",1579,77.90,136.67
13,10103,2003-01-29,2003-02-07,2003-02-02,Shipped,,121,S18_1097,1940 Ford Pickup Truck,Trucks and Buses,1:18,Studio M Art Models,"This model features soft rubber tires, working...",2613,58.33,116.67
14,10103,2003-01-29,2003-02-07,2003-02-02,Shipped,,121,S18_2432,1926 Ford Fire Engine,Trucks and Buses,1:18,Carousel DieCast Legends,Gleaming red handsome appearance. Everything i...,2018,24.92,60.77
15,10103,2003-01-29,2003-02-07,2003-02-02,Shipped,,121,S18_2949,1913 Ford Model T Speedster,Vintage Cars,1:18,Carousel DieCast Legends,This 250 part reproduction includes moving han...,4189,60.78,101.31
16,10103,2003-01-29,2003-02-07,2003-02-02,Shipped,,121,S18_2957,1934 Ford V8 Coupe,Vintage Cars,1:18,Min Lin Diecast,"Chrome Trim, Chrome Grille, Opening Hood, Open...",5649,34.35,62.46
17,10103,2003-01-29,2003-02-07,2003-02-02,Shipped,,121,S18_3136,18th Century Vintage Horse Carriage,Vintage Cars,1:18,Red Start Diecast,Hand crafted diecast-like metal horse carriage...,5992,60.74,104.72
18,10103,2003-01-29,2003-02-07,2003-02-02,Shipped,,121,S18_3320,1917 Maxwell Touring Car,Vintage Cars,1:18,Exoto Designs,"Features Gold Trim, Full Size Spare Tire, Chro...",7913,57.54,99.21
19,10103,2003-01-29,2003-02-07,2003-02-02,Shipped,,121,S18_4600,1940s Ford truck,Trucks and Buses,1:18,Motor City Art Classics,This 1940s Ford Pick-Up truck is re-created in...,3128,84.76,121.08
20,10103,2003-01-29,2003-02-07,2003-02-02,Shipped,,121,S18_4668,1939 Cadillac Limousine,Vintage Cars,1:18,Studio M Art Models,Features completely detailed interior includin...,6645,23.14,50.31
21,10103,2003-01-29,2003-02-07,2003-02-02,Shipped,,121,S24_2300,1962 Volkswagen Microbus,Trucks and Buses,1:24,Autoart Studio Design,This 1:18 scale die cast replica of the 1962 M...,2327,61.34,127.79
22,10103,2003-01-29,2003-02-07,2003-02-02,Shipped,,121,S24_4258,1936 Chrysler Airflow,Vintage Cars,1:24,Second Gear Diecast,"Features opening trunk, working steering syst...",4710,57.46,97.39
23,10103,2003-01-29,2003-02-07,2003-02-02,Shipped,,121,S32_1268,1980’s GM Manhattan Express,Trucks and Buses,1:32,Motor City Art Classics,This 1980’s era new look Manhattan express is ...,5099,53.93,96.31
24,10103,2003-01-29,2003-02-07,2003-02-02,Shipped,,121,S32_3522,1996 Peterbilt 379 Stake Bed with Outrigger,Trucks and Buses,1:32,Red Start Diecast,"This model features, opening doors, detailed e...",814,33.61,64.64
25,10103,2003-01-29,2003-02-07,2003-02-02,Shipped,,121,S700_2824,1982 Camaro Z28,Classic Cars,1:18,Carousel DieCast Legends,Features include opening and closing doors. Co...,6934,46.53,101.15
26,10104,2003-01-31,2003-02-09,2003-02-01,Shipped,,141,S12_3148,1969 Corvair Monza,Classic Cars,1:18,Welly Diecast Productions,"1:18 scale die-cast about 10"" long doors open,...",6906,89.14,151.08
27,10104,2003-01-31,2003-02-09,2003-02-01,Shipped,,141,S12_4473,1957 Chevy Pickup,Trucks and Buses,1:12,Exoto Designs,"1:12 scale die-cast about 20"" long Hood opens,...",6125,55.70,118.50
28,10104,2003-01-31,2003-02-09,2003-02-01,Shipped,,141,S18_2238,1998 Chrysler Plymouth Prowler,Classic Cars,1:18,Gearbox Collectibles,Turnable front wheels; steering function; deta...,4724,101.51,163.73
29,10104,2003-01-31,2003-02-09,2003-02-01,Shipped,,141,S18_2319,1964 Mercedes Tour Bus,Trucks and Buses,1:18,Unimax Art Galleries,Exact replica. 100+ parts. working steering sy...,8258,74.86,122.73
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2966,10420,2005-05-29,2005-06-07,,In Process,,282,S24_3432,2002 Chevy Corvette,Classic Cars,1:24,Gearbox Collectibles,The operating parts of this limited edition Di...,9446,62.11,107.08
2967,10420,2005-05-29,2005-06-07,,In Process,,282,S24_3969,1936 Mercedes Benz 500k Roadster,Vintage Cars,1:24,Red Start Diecast,This model features grille-mounted chrome horn...,2081,21.75,41.03
2968,10421,2005-05-29,2005-06-06,,In Process,Custom shipping instructions were sent to ware...,124,S18_2795,1928 Mercedes-Benz SSK,Vintage Cars,1:18,Gearbox Collectibles,This 1:18 replica features grille-mounted chro...,548,72.56,168.75
2969,10421,2005-05-29,2005-06-06,,In Process,Custom shipping instructions were sent to ware...,124,S24_2022,1938 Cadillac V-16 Presidential Limousine,Vintage Cars,1:24,Classic Metal Creations,This 1:24 scale precision die cast replica of ...,2847,20.61,44.80
2970,10422,2005-05-30,2005-06-11,,In Process,,157,S18_1342,1937 Lincoln Berline,Vintage Cars,1:18,Motor City Art Classics,"Features opening engine cover, doors, trunk, a...",8693,60.62,102.74
2971,10422,2005-05-30,2005-06-11,,In Process,,157,S18_1367,1936 Mercedes-Benz 500K Special Roadster,Vintage Cars,1:18,Studio M Art Models,This 1:18 scale replica is constructed of heav...,8635,24.26,53.91
2972,10423,2005-05-30,2005-06-05,,In Process,,314,S18_2949,1913 Ford Model T Speedster,Vintage Cars,1:18,Carousel DieCast Legends,This 250 part reproduction includes moving han...,4189,60.78,101.31
2973,10423,2005-05-30,2005-06-05,,In Process,,314,S18_2957,1934 Ford V8 Coupe,Vintage Cars,1:18,Min Lin Diecast,"Chrome Trim, Chrome Grille, Opening Hood, Open...",5649,34.35,62.46
2974,10423,2005-05-30,2005-06-05,,In Process,,314,S18_3136,18th Century Vintage Horse Carriage,Vintage Cars,1:18,Red Start Diecast,Hand crafted diecast-like metal horse carriage...,5992,60.74,104.72
2975,10423,2005-05-30,2005-06-05,,In Process,,314,S18_3320,1917 Maxwell Touring Car,Vintage Cars,1:18,Exoto Designs,"Features Gold Trim, Full Size Spare Tire, Chro...",7913,57.54,99.21
2976,10423,2005-05-30,2005-06-05,,In Process,,314,S24_4258,1936 Chrysler Airflow,Vintage Cars,1:24,Second Gear Diecast,"Features opening trunk, working steering syst...",4710,57.46,97.39
2977,10424,2005-05-31,2005-06-08,,In Process,,141,S10_1949,1952 Alpine Renault 1300,Classic Cars,1:10,Classic Metal Creations,Turnable front wheels; steering function; deta...,7305,98.58,214.30
2978,10424,2005-05-31,2005-06-08,,In Process,,141,S12_1666,1958 Setra Bus,Trucks and Buses,1:12,Welly Diecast Productions,"Model features 30 windows, skylights & glare r...",1579,77.90,136.67
2979,10424,2005-05-31,2005-06-08,,In Process,,141,S18_1097,1940 Ford Pickup Truck,Trucks and Buses,1:18,Studio M Art Models,"This model features soft rubber tires, working...",2613,58.33,116.67
2980,10424,2005-05-31,2005-06-08,,In Process,,141,S18_4668,1939 Cadillac Limousine,Vintage Cars,1:18,Studio M Art Models,Features completely detailed interior includin...,6645,23.14,50.31
2981,10424,2005-05-31,2005-06-08,,In Process,,141,S32_3522,1996 Peterbilt 379 Stake Bed with Outrigger,Trucks and Buses,1:32,Red Start Diecast,"This model features, opening doors, detailed e...",814,33.61,64.64
2982,10424,2005-05-31,2005-06-08,,In Process,,141,S700_2824,1982 Camaro Z28,Classic Cars,1:18,Carousel DieCast Legends,Features include opening and closing doors. Co...,6934,46.53,101.15
2983,10425,2005-05-31,2005-06-07,,In Process,,119,S10_4962,1962 LanciaA Delta 16V,Classic Cars,1:10,Second Gear Diecast,Features include: Turnable front wheels; steer...,6791,103.42,147.74
2984,10425,2005-05-31,2005-06-07,,In Process,,119,S12_4473,1957 Chevy Pickup,Trucks and Buses,1:12,Exoto Designs,"1:12 scale die-cast about 20"" long Hood opens,...",6125,55.70,118.50
2985,10425,2005-05-31,2005-06-07,,In Process,,119,S18_2238,1998 Chrysler Plymouth Prowler,Classic Cars,1:18,Gearbox Collectibles,Turnable front wheels; steering function; deta...,4724,101.51,163.73
2986,10425,2005-05-31,2005-06-07,,In Process,,119,S18_2319,1964 Mercedes Tour Bus,Trucks and Buses,1:18,Unimax Art Galleries,Exact replica. 100+ parts. working steering sy...,8258,74.86,122.73
2987,10425,2005-05-31,2005-06-07,,In Process,,119,S18_2432,1926 Ford Fire Engine,Trucks and Buses,1:18,Carousel DieCast Legends,Gleaming red handsome appearance. Everything i...,2018,24.92,60.77
2988,10425,2005-05-31,2005-06-07,,In Process,,119,S18_3232,1992 Ferrari 360 Spider red,Classic Cars,1:18,Unimax Art Galleries,"his replica features opening doors, superb det...",8347,77.90,169.34
2989,10425,2005-05-31,2005-06-07,,In Process,,119,S18_4600,1940s Ford truck,Trucks and Buses,1:18,Motor City Art Classics,This 1940s Ford Pick-Up truck is re-created in...,3128,84.76,121.08
2990,10425,2005-05-31,2005-06-07,,In Process,,119,S24_1444,1970 Dodge Coronet,Classic Cars,1:24,Highway 66 Mini Classics,"1:24 scale die-cast about 18"" long doors open,...",4074,32.37,57.80
2991,10425,2005-05-31,2005-06-07,,In Process,,119,S24_2300,1962 Volkswagen Microbus,Trucks and Buses,1:24,Autoart Studio Design,This 1:18 scale die cast replica of the 1962 M...,2327,61.34,127.79
2992,10425,2005-05-31,2005-06-07,,In Process,,119,S24_2840,1958 Chevy Corvette Limited Edition,Classic Cars,1:24,Carousel DieCast Legends,The operating parts of this 1958 Chevy Corvett...,2542,15.91,35.36
2993,10425,2005-05-31,2005-06-07,,In Process,,119,S32_1268,1980’s GM Manhattan Express,Trucks and Buses,1:32,Motor City Art Classics,This 1980’s era new look Manhattan express is ...,5099,53.93,96.31
2994,10425,2005-05-31,2005-06-07,,In Process,,119,S32_2509,1954 Greyhound Scenicruiser,Trucks and Buses,1:32,Classic Metal Creations,"Model features bi-level seating, 50 windows, s...",2874,25.98,54.11
2995,10425,2005-05-31,2005-06-07,,In Process,,119,S50_1392,Diamond T620 Semi-Skirted Tanker,Trucks and Buses,1:50,Highway 66 Mini Classics,This limited edition model is licensed and per...,1016,68.29,115.75

## Summary

In this lab, you practiced your knowledge on One-to-Many and Many-to-many relationships!